[package]
name = "convergence-arrow"
version = "0.4.1"
authors = ["Ruan Pearce-Authers <ruan@reservoirdb.com>"]
edition = "2018"
description = "Utils for bridging Apache Arrow and PostgreSQL's wire protocol"
license = "MIT"
repository = "https://github.com/reservoirdb/convergence"

[dependencies]
tokio = { version = "1.16" }
sqlparser = "0.18"
async-trait = "0.1"
datafusion = "8"
convergence = { path = "../convergence", version = "0.4.0" }
chrono = "0.4"

[dev-dependencies]
tokio-postgres = { version =  "0.7", features = [ "with-chrono-0_4" ] }
