name: Test

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        toolchain:
        - 1.51.0

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Boot test dependencies
      run: docker-compose up -d

    - name: Run tests
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test

    - name: Run clippy
      uses: actions-rs/cargo@v1.0.3
      with:
        command: clippy
        args: -- -D warnings
